import type { Metadata } from "next";
import { Inter } from "next/font/google";
import HeaderComponent from "@/components/HeaderComponent/HeaderComponent";
import {MovieContext} from "@/context/contextProvider";
import {movieService} from "@/api.service";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Vpadlo Movies",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <HeaderComponent/>
        {children}
        </body>
        </html>
    );
}
