import type { Metadata } from "next";
import HeaderComponent from "@/components/HeaderComponent/HeaderComponent";

export const metadata: Metadata = {
    title: "Vpadlo Movies",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body>
        <HeaderComponent/>
        {children}
        </body>
        </html>
    );
}
